### ISSUE TITLE
自动标注的代码能否分享一下

### ISSUE THREAD

**Issue by gaozhengjie** [qiuhuachuan/latent-jailbreak#2]
您好，请问您使用 KNN 进行自动标注的代码方便分享一下吗？谢谢

**Comment by qiuhuachuan** [comment]
您好，因为准备投稿中，目前代码正在整理，很快会提供哈。上传github后立刻知会您。

感谢您的关注。

**Comment by gaozhengjie** [comment]
感谢，主要是我看了论文中关于自动标注那一块的描述，理解得还是不太清楚，所以看代码更容易搞明白。

您先处理投稿工作，这个事情不急，感谢！

**Comment by qiuhuachuan** [comment]
您好 

之前聚类的方式过于繁琐，我这次直接使用分类模型了。代码和paper已经上传。
